### ISSUE TITLE
CMake on Haiku

### ISSUE THREAD

**Issue by scribam** [cross-platform-actions/action#103]
I am using this in my workflow:
```
- uses: cross-platform-actions/action@v0.28.0
  with:
    operating_system: haiku
    architecture: x86-64
    version: r1beta5
    environment_variables: CCACHE_DIR
    run: |
      pkgman update -y && pkgman install -y ccache cmake git libao libsdl2 libzip lua miniupnpc ninja libcdio
      cmake -B build -DUSE_LIBCDIO=ON -DCMAKE_BUILD_TYPE=Release -G Ninja
      cmake --build build --config Release
```
and I have the following error:
```
A reboot is necessary to complete the installation process.
/bin/bash: line 2: cmake: command not found
```
https://github.com/scribam/flycast/actions/runs/15190011288/job/42720097656#step:4:331

Is there a way to fix this?

**Comment by jacob-carlborg** [comment]
Hmm, that's inconvenient. Is that the case for all packages on Haiku?

It wouldn't be unreasonable to include CMake in the image, although it's not included for the other platforms. But I can't do this for all packages. 

You can always create a custom image: https://github.com/cross-platform-actions/action?tab=readme-ov-file#custom-vm-image-image_url.

**Comment by scribam** [comment]
Thank you for the quick reply!

After further investigation, I don't have the error if I remove the command `pkgman update -y`. This should be enough for me to do that I want 🙂

**Comment by Xottab-DUTY** [comment]
> A reboot is necessary to complete the installation process.

This is for sure inconvenient...
Is there a functionality to reboot the VM?

**Comment by jacob-carlborg** [comment]
> > A reboot is necessary to complete the installation process.
> 
> This is for sure inconvenient...
> Is there a functionality to reboot the VM?

Unfortunately there's not. Is this necessary for many packages? Currently it should work if you create a custom VM image.

**Comment by Xottab-DUTY** [comment]
> Is this necessary for many packages?

It seems to be not needed in my use case.

**Comment by jacob-carlborg** [comment]
@manxorist I've reopened the issue and made the title more general.

**Comment by jacob-carlborg** [comment]
> Maybe there is nothing cross-platform-actions can sensibly do here, except for recommending a custom image

Perhaps adding support for rebooting the VM?

**Comment by jacob-carlborg** [comment]
@manxorist how would one want the reboot feature to look like?

1. As an explicit step, somehow:

```yaml
- uses: cross-platform-actions/action@v0.28.0
  with:
    operating_system: haiku
    architecture: x86-64
    version: r1beta5
    environment_variables: CCACHE_DIR
    run: |
      pkgman update -y && pkgman install -y ccache cmake git libao libsdl2 libzip lua miniupnpc ninja libcdio

- reboot

- uses: cross-platform-actions/action@v0.28.0
  with:
    operating_system: haiku
    architecture: x86-64
    version: r1beta5
    environment_variables: CCACHE_DIR
    run: |
      cmake -B build -DUSE_LIBCDIO=ON -DCMAKE_BUILD_TYPE=Release -G Ninja
      cmake --build build --config Release
```

2. Or a more declarative syntax:

```yaml
- uses: cross-platform-actions/action@v0.28.0
  with:
    operating_system: haiku
    architecture: x86-64
    version: r1beta5
    environment_variables: CCACHE_DIR
    pre_run: |
      pkgman update -y && pkgman install -y ccache cmake git libao libsdl2 libzip lua miniupnpc ninja libcdio
    run: |
      cmake -B build -DUSE_LIBCDIO=ON -DCMAKE_BUILD_TYPE=Release -G Ninja
      cmake --build build --config Release
```

If the `pre_run` parameter is present it would run the command first, then reboot the VM and finally run the regular `run` command. If the `pre_run` parameter is **not** present it would behave as it does today.
