### ISSUE TITLE
Temporary fix for failing to sync files

### ISSUE THREAD

**Issue by albinahlback** [cross-platform-actions/action#51]
I have a problem where, occasionally, the runner cannot sync the files before exiting the emulator. The job seems to work fine, it is just this issue.

As a temporary fix (as I know that this is already reported as an issue in #29), I would like to indicate to the runner that some steps was completed, and that a timeout and error is fine. I did this by setting
```yml
  my-freebsd-job:
    name: FreeBSD
    runs-on: macos-latest
    steps:
      - uses: cross-platform-actions/action@v0.10.0
        timeout-minutes: 25
        continue-on-error: true
        # Create some files if successful
      - name: "next step"
        # Check if the files exist
```
However, if it did time out, the runner will not find the files, regardless of whether it was successful or not. I have also tried to set output variables via `echo "myvar=true" >> $GITHUB_OUTPUT`, but that should also save the variables to a file, so it should also not work.

Perhaps `cross-platform-actions/action` works inside another directory? Perhaps these files exists, just that they are in another directory? If so, what is its path?
