### ISSUE TITLE
FreeBSD on ARM64 fails to acquire an IP

### ISSUE THREAD

**Issue by yorickpeterse** [cross-platform-actions/action#63]
An example is found in https://github.com/inko-lang/inko/actions/runs/6518403904/job/17703959993: the build fails to acquire an IP for the MAC address:

```
  Initializing VM
  Booting VM
  Getting IP address for MAC address: 4e:70:ef:c2:f2:ed
  Waiting for IP to become available...
  Error return from kevent change: Invalid argument
  Consoles: userboot  
  
  FreeBSD/amd64 User boot, Revision 1.1
  (root@fbsd, Sat Jun 20 15:45:53 PDT 2015)
  |/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\Loading /boot/defaults/loader.conf
  |/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/don't know how to load module '/boot/kernel/kernel'
  -\|/-\|/-\
  |/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/can't load 'kernel'
  
  Type '?' for a list of commands, 'help' for more detailed help.
  OK Waiting for IP to become available...
  Waiting for IP to become available...
  Waiting for IP to become available...
  Waiting for IP to become available...
...
```

The configuration for the job is as follows:

```yaml
jobs:
  compiler:
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.68'
          - stable
        arch:
          - x86-64
          - arm64
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ${{ env.CARGO_HOME }}
            target
          key: freebsd-${{ matrix.arch }}-${{ matrix.version }}
      - name: Run tests
        uses: cross-platform-actions/action@v0.19.1
        with:
          operating_system: freebsd
          version: '13.2'
          architecture: '${{ matrix.arch }}'
          environment_variables: 'CARGO_HOME LIBRARY_PATH CARGO_REGISTRIES_CRATES_IO_PROTOCOL'
          hypervisor: qemu
          image_url: 'https://github.com/inko-lang/freebsd-builder/releases/download/v0.6.2/freebsd-13.2-${{ matrix.arch }}.qcow2'
          run: |
            ./scripts/rust.sh ${{ matrix.version }}
            setenv PATH "${CARGO_HOME}/bin:${PATH}"
            echo "::group::Running tests"
            cargo test
            echo "::endgroup::"
```

Did I perhaps misconfigure something?
