### ISSUE TITLE
OpenBSD VM fails during "Initializing VM" with QEMU on macOS

### ISSUE THREAD

**Issue by manxorist** [cross-platform-actions/action#73]
Workflow file <https://github.com/OpenMPT/openmpt/blob/cecc94c82a84bc928cc14eb120453a5334d91e43/.github/workflows/OpenBSD-7.4-Makefile.yml>, relevant parts:
```
jobs:
  build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - uses: cross-platform-actions/action@v0.21.1
      with:
        architecture: x86_64
        hypervisor: qemu
        memory: 4G
        operating_system: openbsd
        version: '7.4'
        sync_files: runner-to-vm
        shell: bash
        run: |
```

(Note that I switched back to xhyve in a later commit, so current master is using OpenBSD on xhyve on macOS)

See
 * https://github.com/OpenMPT/openmpt/actions/runs/6796789166/job/18477596484
 * https://github.com/OpenMPT/openmpt/actions/runs/6796789166/job/18478328282
 * https://github.com/OpenMPT/openmpt/actions/runs/6796789166/job/18478632735

for failing runs
