### ISSUE TITLE
Bad default accelerator

### ISSUE THREAD

**Issue by Caellian** [cross-platform-actions/action#94]
## Version

master (595d543e5d1aeb6d48c0a176965028afe56c7018)

## Options

```yml
uses: cross-platform-actions/action@master
  with:
    environment_variables: ${{env.CONTAINER_ENV}}
    operating_system: openbsd
    architecture: x86-64
    version: 7.6
    shell: bash
```

## Error message

```
qemu: invalid accelerator hvf
```

See [action output](https://github.com/brndnmtthws/conky/actions/runs/11864790470/job/33068865471?pr=2080).
